---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"sidd-harth","password":"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","auth":"c2lkZC1oYXJ0aDpnaHBfS0NtaDRXTDIwZVFjVlllQlpCTlNKdU5HOFdDM3diNDF0QVR6"}}}'
type: kubernetes.io/dockerconfigjson

